export type ResourceItem = { title: string; desc: string; url?: string; type: 'link' | 'download' }
export interface StateResource { slug: string; name: string; legal: ResourceItem[]; contacts: ResourceItem[] }

const NAHB_ITEM: ResourceItem = { title: 'NAHB Consumer Resources', desc: 'National homebuilder consumer guidance and dispute resources', url: 'https://www.nahb.org/other/consumer-resources', type: 'link' }
const DEMAND_LETTER_ITEM: ResourceItem = { title: 'Sample Demand Letter Template', desc: 'Template for formal written demands', url: '/documents/sample-demand-letter-template.txt', type: 'download' }
const BBB_ITEM: ResourceItem = { title: 'Better Business Bureau', desc: 'File builder complaints publicly', url: 'https://www.bbb.org', type: 'link' }

export const stateResources: StateResource[] = [
  {slug:'alabama',name:'Alabama',legal:[{title:'Alabama Construction & Warranty Law',desc:'Alabama statutes governing builder warranties and construction defects',url:'https://alison.legislature.state.al.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Alabama Licensing Board for General Contractors',desc:'File complaints against licensed contractors in Alabama',url:'https://genconbd.alabama.gov',type:'link'},BBB_ITEM]},
  {slug:'alaska',name:'Alaska',legal:[{title:'Alaska Construction & Warranty Law',desc:'Alaska statutes governing builder warranties and construction defects',url:'https://www.akleg.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Alaska Division of Corporations, Business & Professional Licensing',desc:'File complaints against licensed contractors in Alaska',url:'https://www.commerce.alaska.gov/web/cbpl',type:'link'},BBB_ITEM]},
  {slug:'arizona',name:'Arizona',legal:[{title:'Arizona Purchaser Dwelling Act',desc:'A.R.S. Sec. 12-1361 et seq. - notice and right-to-repair requirements for construction defect claims against homebuilders',url:'https://www.azleg.gov/ars/12/01361.htm',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Arizona Registrar of Contractors',desc:'File complaints against licensed contractors in Arizona',url:'https://roc.az.gov',type:'link'},BBB_ITEM]},
  {slug:'arkansas',name:'Arkansas',legal:[{title:'Arkansas Construction & Warranty Law',desc:'Arkansas statutes governing builder warranties and construction defects',url:'https://arkleg.state.ar.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Arkansas Department of Labor and Licensing',desc:'File complaints against licensed contractors in Arkansas',url:'https://labor.arkansas.gov',type:'link'},BBB_ITEM]},
  {slug:'california',name:'California',legal:[{title:'California Construction & Warranty Law',desc:'California statutes governing builder warranties and construction defects',url:'https://leginfo.legislature.ca.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Contractors State License Board (CSLB)',desc:'File complaints against licensed contractors in California',url:'https://www.cslb.ca.gov',type:'link'},BBB_ITEM]},
  {slug:'colorado',name:'Colorado',legal:[{title:'Colorado Construction & Warranty Law',desc:'Colorado statutes governing builder warranties and construction defects',url:'https://leg.colorado.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Colorado Department of Regulatory Agencies (DORA)',desc:'File complaints against licensed contractors in Colorado',url:'https://dora.colorado.gov',type:'link'},BBB_ITEM]},
  {slug:'connecticut',name:'Connecticut',legal:[{title:'Connecticut Construction & Warranty Law',desc:'Connecticut statutes governing builder warranties and construction defects',url:'https://www.cga.ct.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Connecticut Department of Consumer Protection',desc:'File complaints against licensed contractors in Connecticut',url:'https://portal.ct.gov/dcp',type:'link'},BBB_ITEM]},
  {slug:'delaware',name:'Delaware',legal:[{title:'Delaware Construction & Warranty Law',desc:'Delaware statutes governing builder warranties and construction defects',url:'https://legis.delaware.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Delaware Division of Professional Regulation',desc:'File complaints against licensed contractors in Delaware',url:'https://dpr.delaware.gov',type:'link'},BBB_ITEM]},
  {slug:'florida',name:'Florida',legal:[{title:'Florida Construction Defect / Right-to-Cure Law',desc:'Fla. Stat. Sec. 558.001 et seq. - notice and opportunity to repair before filing a construction defect action',url:'https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0500-0599/0558/0558ContentsIndex.html',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Florida Dept. of Business & Professional Regulation (DBPR)',desc:'File complaints against licensed contractors in Florida',url:'https://www.myfloridalicense.com',type:'link'},BBB_ITEM]},
  {slug:'georgia',name:'Georgia',legal:[{title:'Georgia Construction & Warranty Law',desc:'Georgia statutes governing builder warranties and construction defects',url:'https://www.legis.ga.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Georgia Professional Licensing Boards Division (Sec. of State)',desc:'File complaints against licensed contractors in Georgia',url:'https://sos.ga.gov',type:'link'},BBB_ITEM]},
  {slug:'hawaii',name:'Hawaii',legal:[{title:'Hawaii Construction & Warranty Law',desc:'Hawaii statutes governing builder warranties and construction defects',url:'https://www.capitol.hawaii.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Hawaii Contractors License Board',desc:'File complaints against licensed contractors in Hawaii',url:'https://cca.hawaii.gov/pvl',type:'link'},BBB_ITEM]},
  {slug:'idaho',name:'Idaho',legal:[{title:'Idaho Construction & Warranty Law',desc:'Idaho statutes governing builder warranties and construction defects',url:'https://legislature.idaho.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Idaho Contractors Board',desc:'File complaints against licensed contractors in Idaho',url:'https://ibol.idaho.gov',type:'link'},BBB_ITEM]},
  {slug:'illinois',name:'Illinois',legal:[{title:'Illinois Construction & Warranty Law',desc:'Illinois statutes governing builder warranties and construction defects',url:'https://www.ilga.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Illinois Dept. of Financial & Professional Regulation',desc:'File complaints against licensed contractors in Illinois',url:'https://idfpr.illinois.gov',type:'link'},BBB_ITEM]},
  {slug:'indiana',name:'Indiana',legal:[{title:'Indiana Construction & Warranty Law',desc:'Indiana statutes governing builder warranties and construction defects',url:'https://iga.in.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Indiana Professional Licensing Agency',desc:'File complaints against licensed contractors in Indiana',url:'https://www.pla.in.gov',type:'link'},BBB_ITEM]},
  {slug:'iowa',name:'Iowa',legal:[{title:'Iowa Construction & Warranty Law',desc:'Iowa statutes governing builder warranties and construction defects',url:'https://www.legis.iowa.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Iowa Division of Labor',desc:'File complaints against licensed contractors in Iowa',url:'https://labor.iowa.gov',type:'link'},BBB_ITEM]},
  {slug:'kansas',name:'Kansas',legal:[{title:'Kansas Construction & Warranty Law',desc:'Kansas statutes governing builder warranties and construction defects',url:'https://www.kslegislature.org',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Kansas Attorney General Consumer Protection',desc:'File complaints against licensed contractors in Kansas',url:'https://ag.ks.gov',type:'link'},BBB_ITEM]},
  {slug:'kentucky',name:'Kentucky',legal:[{title:'Kentucky Construction & Warranty Law',desc:'Kentucky statutes governing builder warranties and construction defects',url:'https://legislature.ky.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Kentucky Dept. of Housing, Buildings & Construction',desc:'File complaints against licensed contractors in Kentucky',url:'https://dhbc.ky.gov',type:'link'},BBB_ITEM]},
  {slug:'louisiana',name:'Louisiana',legal:[{title:'Louisiana New Home Warranty Act',desc:'La. R.S. \u00a7 9:3141 et seq. \u2014 state law governing new home warranties in Louisiana',url:'https://legis.la.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Louisiana State Licensing Board for Contractors',desc:'File complaints against licensed contractors in Louisiana',url:'https://www.lslbc.louisiana.gov',type:'link'},BBB_ITEM]},
  {slug:'maine',name:'Maine',legal:[{title:'Maine Construction & Warranty Law',desc:'Maine statutes governing builder warranties and construction defects',url:'https://legislature.maine.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Maine Office of Professional & Occupational Regulation',desc:'File complaints against licensed contractors in Maine',url:'https://www.maine.gov/pfr',type:'link'},BBB_ITEM]},
  {slug:'maryland',name:'Maryland',legal:[{title:'Maryland Construction & Warranty Law',desc:'Maryland statutes governing builder warranties and construction defects',url:'https://mgaleg.maryland.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Maryland Home Improvement Commission',desc:'File complaints against licensed contractors in Maryland',url:'https://labor.maryland.gov/license/mhic',type:'link'},BBB_ITEM]},
  {slug:'massachusetts',name:'Massachusetts',legal:[{title:'Massachusetts Construction & Warranty Law',desc:'Massachusetts statutes governing builder warranties and construction defects',url:'https://malegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'MA Office of Consumer Affairs & Business Regulation',desc:'File complaints against licensed contractors in Massachusetts',url:'https://www.mass.gov/orgs/office-of-consumer-affairs-and-business-regulation',type:'link'},BBB_ITEM]},
  {slug:'michigan',name:'Michigan',legal:[{title:'Michigan Construction & Warranty Law',desc:'Michigan statutes governing builder warranties and construction defects',url:'https://www.legislature.mi.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Michigan Dept. of Licensing & Regulatory Affairs (LARA)',desc:'File complaints against licensed contractors in Michigan',url:'https://www.michigan.gov/lara',type:'link'},BBB_ITEM]},
  {slug:'minnesota',name:'Minnesota',legal:[{title:'Minnesota Construction & Warranty Law',desc:'Minnesota statutes governing builder warranties and construction defects',url:'https://www.revisor.mn.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Minnesota Dept. of Labor & Industry',desc:'File complaints against licensed contractors in Minnesota',url:'https://www.dli.mn.gov',type:'link'},BBB_ITEM]},
  {slug:'mississippi',name:'Mississippi',legal:[{title:'Mississippi New Home Warranty Act',desc:'Miss. Code \u00a7\u00a7 83-58-1 to 83-58-17 \u2014 state law governing new home warranties in Mississippi',url:'https://www.legislature.ms.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Mississippi State Board of Contractors',desc:'File complaints against licensed contractors in Mississippi',url:'https://www.msboc.us',type:'link'},BBB_ITEM]},
  {slug:'missouri',name:'Missouri',legal:[{title:'Missouri Construction & Warranty Law',desc:'Missouri statutes governing builder warranties and construction defects',url:'https://house.mo.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Missouri Attorney General Consumer Protection',desc:'File complaints against licensed contractors in Missouri',url:'https://ago.mo.gov',type:'link'},BBB_ITEM]},
  {slug:'montana',name:'Montana',legal:[{title:'Montana Construction & Warranty Law',desc:'Montana statutes governing builder warranties and construction defects',url:'https://leg.mt.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Montana Dept. of Labor & Industry',desc:'File complaints against licensed contractors in Montana',url:'https://dli.mt.gov',type:'link'},BBB_ITEM]},
  {slug:'nebraska',name:'Nebraska',legal:[{title:'Nebraska Construction & Warranty Law',desc:'Nebraska statutes governing builder warranties and construction defects',url:'https://nebraskalegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Nebraska Department of Labor',desc:'File complaints against licensed contractors in Nebraska',url:'https://dol.nebraska.gov',type:'link'},BBB_ITEM]},
  {slug:'nevada',name:'Nevada',legal:[{title:'Nevada Construction & Warranty Law',desc:'Nevada statutes governing builder warranties and construction defects',url:'https://www.leg.state.nv.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Nevada State Contractors Board',desc:'File complaints against licensed contractors in Nevada',url:'https://nvcontractorsboard.com',type:'link'},BBB_ITEM]},
  {slug:'new-hampshire',name:'New Hampshire',legal:[{title:'New Hampshire Construction & Warranty Law',desc:'New Hampshire statutes governing builder warranties and construction defects',url:'https://www.gencourt.state.nh.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'NH Office of Professional Licensure & Certification',desc:'File complaints against licensed contractors in New Hampshire',url:'https://www.oplc.nh.gov',type:'link'},BBB_ITEM]},
  {slug:'new-jersey',name:'New Jersey',legal:[{title:'New Jersey Construction & Warranty Law',desc:'New Jersey statutes governing builder warranties and construction defects',url:'https://www.njleg.state.nj.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'NJ Division of Consumer Affairs',desc:'File complaints against licensed contractors in New Jersey',url:'https://www.njconsumeraffairs.gov',type:'link'},BBB_ITEM]},
  {slug:'new-mexico',name:'New Mexico',legal:[{title:'New Mexico Construction & Warranty Law',desc:'New Mexico statutes governing builder warranties and construction defects',url:'https://nmlegis.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'NM Regulation & Licensing Dept. (Construction Industries Division)',desc:'File complaints against licensed contractors in New Mexico',url:'https://www.rld.nm.gov',type:'link'},BBB_ITEM]},
  {slug:'new-york',name:'New York',legal:[{title:'New York Construction & Warranty Law',desc:'New York statutes governing builder warranties and construction defects',url:'https://www.nysenate.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'NY Dept. of State Division of Licensing Services',desc:'File complaints against licensed contractors in New York',url:'https://www.dos.ny.gov/licensing',type:'link'},BBB_ITEM]},
  {slug:'north-carolina',name:'North Carolina',legal:[{title:'North Carolina Construction & Warranty Law',desc:'North Carolina statutes governing builder warranties and construction defects',url:'https://www.ncleg.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'NC Licensing Board for General Contractors',desc:'File complaints against licensed contractors in North Carolina',url:'https://www.nclbgc.org',type:'link'},BBB_ITEM]},
  {slug:'north-dakota',name:'North Dakota',legal:[{title:'North Dakota Construction & Warranty Law',desc:'North Dakota statutes governing builder warranties and construction defects',url:'https://www.legis.nd.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'ND Secretary of State \u2014 Contractor Licensing',desc:'File complaints against licensed contractors in North Dakota',url:'https://www.sos.nd.gov',type:'link'},BBB_ITEM]},
  {slug:'ohio',name:'Ohio',legal:[{title:'Ohio Construction & Warranty Law',desc:'Ohio statutes governing builder warranties and construction defects',url:'https://www.legislature.ohio.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Ohio Construction Industry Licensing Board',desc:'File complaints against licensed contractors in Ohio',url:'https://com.ohio.gov',type:'link'},BBB_ITEM]},
  {slug:'oklahoma',name:'Oklahoma',legal:[{title:'Oklahoma Construction & Warranty Law',desc:'Oklahoma statutes governing builder warranties and construction defects',url:'https://www.oklegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Oklahoma Construction Industries Board',desc:'File complaints against licensed contractors in Oklahoma',url:'https://www.cib.ok.gov',type:'link'},BBB_ITEM]},
  {slug:'oregon',name:'Oregon',legal:[{title:'Oregon Construction & Warranty Law',desc:'Oregon statutes governing builder warranties and construction defects',url:'https://www.oregonlegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Oregon Construction Contractors Board',desc:'File complaints against licensed contractors in Oregon',url:'https://www.oregon.gov/ccb',type:'link'},BBB_ITEM]},
  {slug:'pennsylvania',name:'Pennsylvania',legal:[{title:'Pennsylvania Construction & Warranty Law',desc:'Pennsylvania statutes governing builder warranties and construction defects',url:'https://www.legis.state.pa.us',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'PA Office of Attorney General \u2014 Home Improvement Consumer Protection',desc:'File complaints against licensed contractors in Pennsylvania',url:'https://www.attorneygeneral.gov',type:'link'},BBB_ITEM]},
  {slug:'rhode-island',name:'Rhode Island',legal:[{title:'Rhode Island Construction & Warranty Law',desc:'Rhode Island statutes governing builder warranties and construction defects',url:'https://www.rilegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'RI Contractors\u2019 Registration & Licensing Board',desc:'File complaints against licensed contractors in Rhode Island',url:'https://dbr.ri.gov/divisions/contractors',type:'link'},BBB_ITEM]},
  {slug:'south-carolina',name:'South Carolina',legal:[{title:'South Carolina Construction & Warranty Law',desc:'South Carolina statutes governing builder warranties and construction defects',url:'https://www.scstatehouse.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'SC Dept. of Labor, Licensing & Regulation',desc:'File complaints against licensed contractors in South Carolina',url:'https://www.llr.sc.gov',type:'link'},BBB_ITEM]},
  {slug:'south-dakota',name:'South Dakota',legal:[{title:'South Dakota Construction & Warranty Law',desc:'South Dakota statutes governing builder warranties and construction defects',url:'https://sdlegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'SD Dept. of Labor & Regulation',desc:'File complaints against licensed contractors in South Dakota',url:'https://dlr.sd.gov',type:'link'},BBB_ITEM]},
  {slug:'tennessee',name:'Tennessee',legal:[{title:'Tennessee Construction & Warranty Law',desc:'Tennessee statutes governing builder warranties and construction defects',url:'https://www.capitol.tn.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'TN Board for Licensing Contractors',desc:'File complaints against licensed contractors in Tennessee',url:'https://www.tn.gov/commerce',type:'link'},BBB_ITEM]},
  {slug:'texas',name:'Texas',legal:[{title:'Texas Residential Construction Liability Act (RCLA)',desc:'Tex. Prop. Code Sec. 27.001 et seq. - notice-and-opportunity-to-cure process homeowners must follow before suing a builder',url:'https://statutes.capitol.texas.gov/Docs/PR/htm/PR.27.htm',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Texas Dept. of Licensing & Regulation (TDLR)',desc:'File complaints against licensed contractors in Texas',url:'https://www.tdlr.texas.gov',type:'link'},BBB_ITEM]},
  {slug:'utah',name:'Utah',legal:[{title:'Utah New Home Warranty Act',desc:'Utah Code \u00a7 58-70a \u2014 state law governing builder warranties in Utah',url:'https://le.utah.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Utah Division of Professional Licensing (DOPL)',desc:'File complaints against licensed contractors in Utah',url:'https://dopl.utah.gov',type:'link'},BBB_ITEM]},
  {slug:'vermont',name:'Vermont',legal:[{title:'Vermont Construction & Warranty Law',desc:'Vermont statutes governing builder warranties and construction defects',url:'https://legislature.vermont.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'VT Office of Professional Regulation',desc:'File complaints against licensed contractors in Vermont',url:'https://sos.vermont.gov/opr',type:'link'},BBB_ITEM]},
  {slug:'virginia',name:'Virginia',legal:[{title:'Virginia Construction & Warranty Law',desc:'Virginia statutes governing builder warranties and construction defects',url:'https://law.lis.virginia.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'VA Dept. of Professional & Occupational Regulation (DPOR)',desc:'File complaints against licensed contractors in Virginia',url:'https://www.dpor.virginia.gov',type:'link'},BBB_ITEM]},
  {slug:'washington',name:'Washington',legal:[{title:'Washington Construction & Warranty Law',desc:'Washington statutes governing builder warranties and construction defects',url:'https://leg.wa.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'WA Dept. of Labor & Industries',desc:'File complaints against licensed contractors in Washington',url:'https://www.lni.wa.gov',type:'link'},BBB_ITEM]},
  {slug:'west-virginia',name:'West Virginia',legal:[{title:'West Virginia Construction & Warranty Law',desc:'West Virginia statutes governing builder warranties and construction defects',url:'https://www.wvlegislature.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'WV Division of Labor',desc:'File complaints against licensed contractors in West Virginia',url:'https://labor.wv.gov',type:'link'},BBB_ITEM]},
  {slug:'wisconsin',name:'Wisconsin',legal:[{title:'Wisconsin Construction & Warranty Law',desc:'Wisconsin statutes governing builder warranties and construction defects',url:'https://docs.legis.wisconsin.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'WI Dept. of Safety & Professional Services',desc:'File complaints against licensed contractors in Wisconsin',url:'https://dsps.wi.gov',type:'link'},BBB_ITEM]},
  {slug:'wyoming',name:'Wyoming',legal:[{title:'Wyoming Construction & Warranty Law',desc:'Wyoming statutes governing builder warranties and construction defects',url:'https://www.wyoleg.gov',type:'link'},NAHB_ITEM,DEMAND_LETTER_ITEM],contacts:[{title:'Wyoming Attorney General Consumer Protection',desc:'File complaints against licensed contractors in Wyoming',url:'https://ag.wyo.gov',type:'link'},BBB_ITEM]},
  ]

export function getStateBySlug(slug: string): StateResource | undefined {
  return stateResources.find(s => s.slug === slug)
}

export function getAllStateSlugs(): string[] {
  return stateResources.map(s => s.slug)
}
